### ISSUE TITLE
Installation was not succeded

### ISSUE THREAD

**Issue by okantopcu** [RecordEvolution/IMCtermite#17]
I tried to install this package using pip but it did not work. In the attached picture, you may see the problem. I would be appreciate if anyone could help me with this issue.
![Capture2](https://user-images.githubusercontent.com/12495620/216055789-31997578-7971-491b-b1c2-6895ec4c9eeb.JPG)

**Comment by mario-fink** [comment]
@okantopcu Can you please provide some information on the system/architecture you're using ?

**Comment by okantopcu** [comment]
dear mario, i guess the information in the attached files would be sufficient. But if you need further questions, i can provide more information. Thanks for your reply, by the way.
![Capture](https://user-images.githubusercontent.com/12495620/216245031-fb8fc547-025b-4b0c-8557-3bb6521c18c0.JPG)
![Capture1](https://user-images.githubusercontent.com/12495620/216245056-6ec321cc-1cb3-4b1e-96eb-0390b23acd6a.JPG)

**Comment by okantopcu** [comment]
I guess the problem arises from the wrong placed lib folder. It should be placed under pyhton folder. Otherwise, the source file can not be found and installation can not be carried out.

**Comment by mario-fink** [comment]
Building python wheels on Windows wasn't considered so far since the python wheels are usually built using the make framework on linux/mac (see e.g. github workflows). By the way, if you miss binary wheels for any OS, arch or python version, please let me know! So I'm afraid, for the time being you have to copy lib/ to the python directory to build on windows.
